import Link from "next/link";
import { pageMetadata } from "@/lib/metadata";
export const metadata = pageMetadata("Privacy policy", "How FyreLinkz handles browsing, optional analytics, advertising links and your privacy choices.", "/privacy");
export default function Privacy() {
  return <div className="wrap info-page">
    <span className="eyebrow">SITE INFORMATION · UPDATED 20 SEPTEMBER 2026</span>
    <h1>Privacy<span>.</span></h1>
    <p className="intro">Useful information. Clear choices. How we handle data when you use FyreLinkz.</p>
    <section><h2>Who and what this covers</h2><p>This notice covers fyrelinkz.com, our articles, search, model directory. FyreLinkz is an independent publication. Contact the publisher at <a href="mailto:editorial@fyrelinkz.com">editorial@fyrelinkz.com</a> about privacy or corrections.</p></section>
    <section><h2>Site search</h2><p>Search queries are processed in your browser. You do not need an account, and we do not submit your search text to an editorial database.</p></section>
    <section><h2>Hosting and technical information</h2><p>Visiting this site sends your IP address, requested URL and technical browser information to our hosting infrastructure to deliver pages, maintain reliability and prevent abuse. The production website uses Vercel. Its processing and retention depend on service settings and its <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">privacy notice</a>. We do not use a visitor account database.</p></section>
    <section><h2>Optional analytics and cookies</h2><p>If Google Analytics is configured, we request permission before loading its tag. With consent, it measures visits, reading, source-link and RSS interactions. Google may receive browser and device information, cookie identifiers and technical request data. Analytics cookies distinguish visits. Search text is excluded from our events; only approved campaign parameters are included in the page address sent to Analytics. Advertising personalization and Google Signals are disabled.</p><p>Declining keeps all site features available without the tag. When analytics is configured, the Analytics preferences control lets you change your choice. Withdrawal stops subsequent tracking calls and removes accessible Google Analytics cookies on our domain; it does not erase data already received by Google. Your choice stays in this browser until changed or site storage is cleared. Do Not Track and Global Privacy Control disable this optional tracking.</p><p>See <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google’s privacy policy</a> and its explanation of <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">data from partner sites</a>. You can control cookies in your browser. Analytics retention depends on the configured property; no unconfigured account retention period is claimed here.</p></section>
    <section><h2>Advertising and external links</h2><p>Paid placements are marked “Advertisement” and commercial links are identified in the page markup. Direct sponsor links do not load an ad-network tracking script. Advertiser and source websites have their own privacy practices. See <Link href="/about#funding">how the site is funded</Link>.</p><p>This version does not serve Google AdSense or personalized network ads. Before introducing network ads, we will update this notice with the active vendors, purposes, cookies and privacy choices. Google and other advertising vendors may then use cookies to serve and measure ads based on visits to this and other sites. Google’s personalization choices are in <a href="https://myadcenter.google.com/" target="_blank" rel="noopener noreferrer">My Ad Center</a>; participating vendors also offer choices through the <a href="https://optout.aboutads.info/" target="_blank" rel="noopener noreferrer">Digital Advertising Alliance</a>. These links do not replace consent controls on this site.</p></section>
    <section><h2>Email, retention and your requests</h2><p>Emailing us shares your address and message with the recipient and email providers to respond. Avoid sending sensitive information. Request access, correction or deletion of personal information held by the publisher, or ask about applicable privacy rights, through the contact above. We may need enough information to verify and locate the request. Information needed for legal obligations or a dispute may need to be retained.</p><p>Hosting, email and optional analytics providers may process information in other countries under their terms and safeguards. We do not run a newsletter subscriber database or sell a reader contact list in this version.</p></section>
    <section><h2>Changes</h2><p>We revise this notice when features or practices change. The date above identifies the latest revision. A future ad integration requires applicable consent and opt-out controls; our optional analytics preference is not an advertising consent platform.</p></section>
  </div>;
}
