import Link from "next/link";
import ModelDirectory from "@/components/ModelDirectory";
import JsonLd from "@/components/JsonLd";
import {pageMetadata} from "@/lib/metadata";
import {SITE_URL} from "@/lib/editorial";
import {VIDEO_VARIANTS, PRICING_CHECKED} from "@/lib/video-plans";
export const metadata=pageMetadata("AI video models & credit prices: Higgsfield, Runway, Luma, Pika", "Compare AI video model credit rates by platform, resolution and duration. Browse Kling, Seedance, Veo, Sora, Hailuo, Ray and Pika, with original sources.", "/ai-video-models");
export default function VideoModels() {
  return <div className="wrap directory-page"><JsonLd data={{"@context":"https://schema.org","@type":"CollectionPage",name:"AI video model and credit directory",url:SITE_URL+"/ai-video-models",dateModified:PRICING_CHECKED,isAccessibleForFree:true}}/><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>Video models</span></nav><header className="directory-header"><span className="eyebrow">THE MODEL INDEX</span><h1>Know the model.<br/><span>Know the credit cost.</span></h1><p>Compare {VIDEO_VARIANTS.length} model and output configurations across four platforms. Understand the options and verify current rates with the original provider.</p><div className="tool-trust"><span>4 platforms</span><span>12 base paid plans</span><span>Checked {PRICING_CHECKED}</span></div></header><ModelDirectory/><section className="tool-methodology"><h2>A model is not a subscription.</h2><p>Kling, Seedance, Sora and Veo can be offered through different platforms. A Higgsfield credit, Runway credit and Luma credit have different buying power. Compare the actual payment, settings and usable output—not credit counts alone.</p><p>This is a snapshot of the public catalogs checked above, including generation, motion, editing and lip-sync modes where listed. It is not a claim to include every model on the internet. Some newly listed models require an account quote. Free trials, business contracts, API billing, promotions and extra-credit packs are outside this base-plan comparison.</p><Link href="/create/ai-video-generation-matrix-minimax-higgsfield-seedance" className="button-primary">Read the model selection guide ↗</Link></section></div>;
}
